sudo: required
services:
  - docker

before_install:
  - docker build -t fbruton/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fbruton/react-test npm test

after_success:
  - docker build -t fbruton/multi-client ./client
  - docker build -t fbruton/multi-nginx ./nginx
  - docker build -t fbruton/multi-server ./server
  - docker build -t fbruton/multi-worker ./worker
  # Login to docker CLI
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push fbruton/multi-client
  - docker push fbruton/multi-nginx
  - docker push fbruton/multi-server
  - docker push fbruton/multi-worker